[workspace]
resolver = "3"
members = [
    #"backend",
    "oneclick",
    "transfer",
    "workers/beatmap-worker"
]

[workspace.package]
version = "2.0.0"
edition = "2024"

[profile.dev]
opt-level = 1
lto = false

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
strip = true
codegen-units = 1

[workspace.lints.rust]
warnings = "deny"
future-incompatible = "deny"
let-underscore = "deny"
nonstandard-style = "deny"
refining-impl-trait = "deny"
unused = "deny"

# Strict lints, should not be changed.
[workspace.lints.clippy]
all = "deny"
cargo = "deny"
complexity = "deny"
correctness = "deny"
nursery = "deny"
pedantic = "deny"
perf = "deny"
restriction = "deny"
style = "deny"
suspicious = "deny"
as_conversions = { level = "allow", priority = 1 }
allow_attributes = { level = "allow", priority = 1 }
arbitrary_source_item_ordering = { level = "allow", priority = 1 }
cast_precision_loss = { level = "allow", priority = 1 }
else_if_without_else = { level = "allow", priority = 1 }
multiple_crate_versions = { level = "allow", priority = 1 }
module_name_repetitions = { level = "allow", priority = 1 }
mod_module_files = { level = "allow", priority = 1 }
blanket_clippy_restriction_lints = { level = "allow", priority = 1 }
cargo_common_metadata = { level = "allow", priority = 1 }
cast_possible_truncation = { level = "allow", priority = 1 }
pub_with_shorthand = { level = "allow", priority = 1 }
exhaustive_structs = { level = "allow", priority = 1 }
unseparated_literal_suffix = { level = "allow", priority = 1 }
float_arithmetic = { level = "allow", priority = 1 }
pub_use = { level = "allow", priority = 1 }
must_use_candidate = { level = "allow", priority = 1 }
exhaustive_enums = { level = "allow", priority = 1 }
too-long-first-doc-paragraph = { level = "allow", priority = 1 }
implicit_return = { level = "allow", priority = 1 }
single_call_fn = { level = "allow", priority = 1 }
question_mark_used = { level = "allow", priority = 1 }
wildcard_imports = { level = "allow", priority = 1 }
wildcard_enum_match_arm = { level = "allow", priority = 1 }